name: Show Code Coverage
on:
  pull_request:
    branches:
      # should be replaced with "main"
      - enable-codecoverage-pipeline
  push:
    branches:
      # should be replaced with "main"
      - enable-codecoverage-pipeline


jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Image And CUDA Quantum
        id: cudaq_build
        run: |
          docker build -t cuda-quantum-cc:local -f docker/build/cudaq.cc.Dockerfile . \
            --build-arg install="CMAKE_BUILD_TYPE=Debug CUDAQ_ENABLE_CC=ON LLVM_PROFILE_FILE=/tmp/cudaq-cc/profile-%9m.profraw"

      - name: Create Shared Dir
        run: |
          mkdir -p /home/runner/work/shared

      - name: Test CUDA Quantum And Generate CC
        uses: addnab/docker-run-action@v3
        with:
          image: cuda-quantum-cc:local
          options: -v /home/runner/work/shared:/shared
          shell: bash
          run: |
            cd $CUDAQ_REPO_ROOT
            export LLVM_PROFILE_FILE=/tmp/cudaq-cc/profile-%9m.profraw
            ctest --output-on-failure --test-dir build -E ctest-nvqpp
            ctest_status=$?
            /opt/llvm/llvm-project/build/bin/llvm-lit -v --param nvqpp_site_config=build/test/lit.site.cfg.py build/test
            lit_status=$?
            llvm-profdata merge -sparse /tmp/cudaq-cc/profile-*.profraw -o coverage.profdata
            binarys=($(sed -n -e '/Linking CXX shared library/s/^.*Linking CXX shared library //p' \
             -e '/Linking CXX executable/s/^.*Linking CXX executable //p' /workspaces/cuda-quantum/build/logs/ninja_output.txt))
            objects=""
            for item in "${binarys[@]}"; do
              objects+="-object /workspaces/cuda-quantum/build/$item "
            done
            llvm-cov show ${objects} -instr-profile=coverage.profdata --ignore-filename-regex="/workspaces/cuda-quantum/tpls/*" \
             --ignore-filename-regex="/workspaces/cuda-quantum/build/*" > coverage.txt
            cp ./coverage.txt /shared
            if [ ! $ctest_status -eq 0 ] || [ ! $lit_status -eq 0 ]; then
              echo "ctest status = " $ctest_status
              echo "llvm-lit status = " $lit_status
            fi

      - name: Upload Coverage To Codecov
        uses: codecov/codecov-action@v3
        with:
          files: /home/runner/work/shared/coverage.txt
          verbose: true
